# Note: If you update this, make sure to update tox.ini, too.
sudo: false
language: python
cache:
  directories:
  - "~/.cache/pip"

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install -U pip setuptools>=18.5
  - pip install -r requirements-dev.txt

matrix:
  include:
    - python: 2.7
      env: MODE=lint
    - python: 2.7
      env: MODE=vendorverify
    - python: 3.4
      env: MODE=lint

script:
  - ./scripts/run_tests.sh $MODE
