# Note: If you update this, make sure to update tox.ini, too.
dist: xenial
language: python
cache:
  directories:
  - "~/.cache/pip"

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

install:
  - pip install -U pip setuptools>=18.5
  - pip install -r requirements-dev.txt

matrix:
  include:
    - python: "3.8"
      env: MODE=vendorverify
    - python: "3.8"
      env: MODE=lint
    - python: "3.8"
      env: MODE=format-check
      install:
        - pip install -U pip setuptools>=18.5
        - pip install -r requirements-dev.txt
        - pip install -U black
    - python: "3.6"
      env: MODE=docs

script:
  - ./scripts/run_tests.sh $MODE
